/**
 * Claude-Powered Universal Plugin & Extension Detection System
 * Detects and categorizes plugins/extensions for WordPress and top 100 CMS platforms
 */

import Anthropic from '@anthropic-ai/sdk';

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

export interface DetectedPlugin {
  name: string;
  category: 'security' | 'performance' | 'seo' | 'ecommerce' | 'analytics' | 'social' | 'backup' | 'forms' | 'page-builder' | 'content' | 'payment' | 'marketing' | 'integration' | 'utility' | 'theme' | 'other';
  subcategory?: string;
  confidence: 'high' | 'medium' | 'low';
  version?: string;
  description: string;
  riskLevel: 'low' | 'medium' | 'high' | 'critical';
  performanceImpact: 'minimal' | 'low' | 'medium' | 'high';
  recommendations: string[];
  detectionEvidence: string[];
}

export interface PlatformAnalysis {
  platform: string;
  platformVersion?: string;
  totalPluginsDetected: number;
  pluginsByCategory: Record<string, DetectedPlugin[]>;
  securityAssessment: {
    overallRisk: 'low' | 'medium' | 'high' | 'critical';
    vulnerablePlugins: DetectedPlugin[];
    recommendations: string[];
  };
  performanceAnalysis: {
    heavyPlugins: DetectedPlugin[];
    optimizationOpportunities: string[];
    estimatedSpeedImpact: string;
  };
  businessInsights: {
    pluginPurpose: string;
    businessType: string;
    recommendedImprovements: string[];
    missingEssentials: string[];
  };
  conflicts: {
    redundantPlugins: string[];
    potentialConflicts: string[];
  };
}

export async function detectPluginsWithClaude(
  platform: string,
  htmlContent: string,
  headers: Record<string, string>,
  url: string
): Promise<PlatformAnalysis> {
  try {
    console.log(`🧠 Analyzing ${platform} plugins and extensions with Claude for ${url}`);

    // Analyze HTML for content clues
    const contentLength = htmlContent.length;
    const scriptCount = (htmlContent.match(/<script[^>]*>/gi) || []).length;
    const linkCount = (htmlContent.match(/<link[^>]*>/gi) || []).length;
    const formCount = (htmlContent.match(/<form[^>]*>/gi) || []).length;
    
    // Extract key HTML sections for analysis
    const headSection = htmlContent.match(/<head[^>]*>([\s\S]*?)<\/head>/i)?.[1] || '';
    const scriptTags = htmlContent.match(/<script[^>]*>[\s\S]*?<\/script>/gi) || [];
    const linkTags = htmlContent.match(/<link[^>]*>/gi) || [];
    const metaTags = htmlContent.match(/<meta[^>]*>/gi) || [];
    
    // Prepare comprehensive content sample for Claude
    const analysisContent = {
      htmlSample: htmlContent.substring(0, 8000), // First 8KB for context
      headSection: headSection.substring(0, 3000),
      scriptSources: scriptTags.slice(0, 20).map(tag => {
        const src = tag.match(/src=["']([^"']+)["']/)?.[1];
        return src ? src.substring(src.lastIndexOf('/') + 1) : 'inline';
      }),
      linkSources: linkTags.slice(0, 15).map(tag => {
        const href = tag.match(/href=["']([^"']+)["']/)?.[1];
        return href ? href.substring(href.lastIndexOf('/') + 1) : 'unknown';
      }),
      metaInfo: metaTags.slice(0, 10),
      serverHeaders: Object.keys(headers).map(key => `${key}: ${headers[key]}`).slice(0, 10)
    };

    // Generate platform-aware prompt
    const prompt = generatePlatformAwarePrompt(
      platform,
      url,
      contentLength,
      scriptCount,
      linkCount,
      formCount,
      analysisContent
    );

    // Use platform-aware prompt (generated by helper function)
    const response = await anthropic.messages.create({
      model: 'claude-3-haiku-20240307',
      max_tokens: 4000,
      messages: [
        {
          role: 'user',
          content: prompt
        }
      ]
    });

    const content = response.content[0];
    if (content.type !== 'text') {
      throw new Error('Unexpected response format from Claude');
    }

    try {
      // Enhanced JSON extraction with multiple strategies
      let jsonText = content.text.trim();

      // Strategy 1: Find JSON between first { and last }
      const firstBrace = jsonText.indexOf('{');
      const lastBrace = jsonText.lastIndexOf('}');

      if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
        jsonText = jsonText.substring(firstBrace, lastBrace + 1);
      }

      // Strategy 2: Remove markdown code blocks if present
      jsonText = jsonText.replace(/```json\s*/g, '').replace(/```\s*/g, '');

      // Strategy 3: Fix common JSON issues
      // Remove control characters that break JSON parsing
      jsonText = jsonText.replace(/[\x00-\x1F\x7F-\x9F]/g, '');

      // Strategy 4: Handle escaped newlines in strings
      jsonText = jsonText.replace(/\\n/g, ' ').replace(/\n/g, ' ');

      // Strategy 5: Fix trailing commas (common Claude mistake)
      jsonText = jsonText.replace(/,(\s*[}\]])/g, '$1');

      let analysis;
      try {
        analysis = JSON.parse(jsonText);
      } catch (parseError) {
        console.error('Failed to parse Claude plugin response:', parseError);
        console.error('📄 Raw response length:', content.text.length, 'chars');
        console.error('📄 First 500 chars:', content.text.substring(0, 500));
        console.error('📄 Last 200 chars:', content.text.substring(content.text.length - 200));
        console.log('🔄 Using fallback plugin analysis due to JSON parsing error');
        return getFallbackPluginAnalysis(platform);
      }
      
      // Process the analysis into our expected format
      const processedAnalysis: PlatformAnalysis = {
        platform: analysis.platform || platform,
        platformVersion: analysis.platformVersion,
        totalPluginsDetected: analysis.detectedPlugins?.length || 0,
        pluginsByCategory: {},
        securityAssessment: {
          overallRisk: analysis.securityAssessment?.overallRisk || 'low',
          vulnerablePlugins: [],
          recommendations: analysis.securityAssessment?.recommendations || []
        },
        performanceAnalysis: {
          heavyPlugins: [],
          optimizationOpportunities: analysis.performanceAnalysis?.optimizationOpportunities || [],
          estimatedSpeedImpact: analysis.performanceAnalysis?.estimatedSpeedImpact || 'minimal impact detected'
        },
        businessInsights: {
          pluginPurpose: analysis.businessInsights?.pluginPurpose || 'Standard website functionality',
          businessType: analysis.businessInsights?.businessType || 'General website',
          recommendedImprovements: analysis.businessInsights?.recommendedImprovements || [],
          missingEssentials: analysis.businessInsights?.missingEssentials || []
        },
        conflicts: {
          redundantPlugins: analysis.conflicts?.redundantPlugins || [],
          potentialConflicts: analysis.conflicts?.potentialConflicts || []
        }
      };

      // Categorize plugins
      if (analysis.detectedPlugins) {
        for (const plugin of analysis.detectedPlugins) {
          const category = plugin.category || 'other';
          if (!processedAnalysis.pluginsByCategory[category]) {
            processedAnalysis.pluginsByCategory[category] = [];
          }
          processedAnalysis.pluginsByCategory[category].push(plugin);

          // Add to vulnerable plugins if high risk
          if (plugin.riskLevel === 'high' || plugin.riskLevel === 'critical') {
            processedAnalysis.securityAssessment.vulnerablePlugins.push(plugin);
          }

          // Add to heavy plugins if high performance impact
          if (plugin.performanceImpact === 'high' || plugin.performanceImpact === 'medium') {
            processedAnalysis.performanceAnalysis.heavyPlugins.push(plugin);
          }
        }
      }

      console.log(`✅ Claude plugin analysis complete for ${platform}: ${processedAnalysis.totalPluginsDetected} plugins detected`);
      return processedAnalysis;

    } catch (parseError) {
      console.error('Failed to parse Claude plugin response:', parseError);
      console.log('Raw response:', content.text);
      
      // Return fallback analysis
      return getFallbackPluginAnalysis(platform);
    }

  } catch (error) {
    console.error('Claude plugin analysis failed:', error);
    return getFallbackPluginAnalysis(platform);
  }
}

function getFallbackPluginAnalysis(platform: string): PlatformAnalysis {
  return {
    platform,
    totalPluginsDetected: 0,
    pluginsByCategory: {},
    securityAssessment: {
      overallRisk: 'low',
      vulnerablePlugins: [],
      recommendations: ['Unable to perform detailed security analysis', 'Consider manual plugin review']
    },
    performanceAnalysis: {
      heavyPlugins: [],
      optimizationOpportunities: ['Unable to analyze plugin performance impact'],
      estimatedSpeedImpact: 'Analysis not available'
    },
    businessInsights: {
      pluginPurpose: 'Unable to determine from available data',
      businessType: 'Unknown',
      recommendedImprovements: ['Consider comprehensive plugin audit'],
      missingEssentials: ['Analysis not available']
    },
    conflicts: {
      redundantPlugins: [],
      potentialConflicts: []
    }
  };
}

// Universal plugin detection for all major CMS platforms
export async function detectUniversalPlugins(
  htmlContent: string,
  headers: Record<string, string>,
  url: string,
  detectedCMS?: string
): Promise<PlatformAnalysis> {
  
  // If we already know the CMS, use it, otherwise detect it
  let platform = detectedCMS;
  
  if (!platform) {
    platform = detectPlatformFromHTML(htmlContent, headers);
  }
  
  console.log(`🔍 Detected platform: ${platform} for universal plugin analysis`);
  
  return await detectPluginsWithClaude(platform, htmlContent, headers, url);
}

// Platform detection helper
function detectPlatformFromHTML(html: string, headers: Record<string, string>): string {
  const lowerHtml = html.toLowerCase();
  
  // WordPress detection
  if (lowerHtml.includes('/wp-content/') || lowerHtml.includes('/wp-includes/') || lowerHtml.includes('wp-emoji')) {
    return 'WordPress';
  }
  
  // Shopify detection
  if (lowerHtml.includes('shopify') && (lowerHtml.includes('cdn.shopify.com') || lowerHtml.includes('shopify-analytics'))) {
    return 'Shopify';
  }
  
  // Drupal detection
  if (lowerHtml.includes('/sites/default/files/') || lowerHtml.includes('drupal.js') || lowerHtml.includes('drupal.settings')) {
    return 'Drupal';
  }
  
  // Webflow detection
  if (lowerHtml.includes('webflow.com') || lowerHtml.includes('webflow-assets') || lowerHtml.includes('webflow.css')) {
    return 'Webflow';
  }
  
  // Squarespace detection
  if (lowerHtml.includes('squarespace') || lowerHtml.includes('squarespace-cdn') || lowerHtml.includes('static1.squarespace.com')) {
    return 'Squarespace';
  }
  
  // Wix detection
  if (lowerHtml.includes('wix.com') || lowerHtml.includes('wixstatic.com') || lowerHtml.includes('wix-code')) {
    return 'Wix';
  }
  
  // Joomla detection
  if (lowerHtml.includes('/media/jui/') || lowerHtml.includes('joomla') || lowerHtml.includes('mootools')) {
    return 'Joomla';
  }
  
  // Magento detection
  if (lowerHtml.includes('mage/') || lowerHtml.includes('magento') || lowerHtml.includes('varien/')) {
    return 'Magento';
  }
  
  // PrestaShop detection
  if (lowerHtml.includes('prestashop') || lowerHtml.includes('/modules/') && lowerHtml.includes('/themes/')) {
    return 'PrestaShop';
  }
  
  // Ghost detection
  if (lowerHtml.includes('ghost.org') || lowerHtml.includes('ghost-url') || lowerHtml.includes('ghost.min.css')) {
    return 'Ghost';
  }
  
  // HubSpot detection
  if (lowerHtml.includes('hubspot') || lowerHtml.includes('hs-scripts.com') || lowerHtml.includes('hsforms.net')) {
    return 'HubSpot CMS';
  }
  
  // Contentful detection
  if (lowerHtml.includes('contentful') || lowerHtml.includes('ctfassets.net')) {
    return 'Contentful';
  }
  
  // Strapi detection
  if (lowerHtml.includes('strapi') || headers['x-powered-by']?.toLowerCase().includes('strapi')) {
    return 'Strapi';
  }
  
  // Next.js detection
  if (lowerHtml.includes('__next') || lowerHtml.includes('_buildmanifest') || lowerHtml.includes('next.js')) {
    return 'Next.js';
  }
  
  // Gatsby detection
  if (lowerHtml.includes('gatsby') || lowerHtml.includes('___gatsby')) {
    return 'Gatsby';
  }
  
  // React detection (fallback)
  if (lowerHtml.includes('react') || lowerHtml.includes('_react') || lowerHtml.includes('__react')) {
    return 'React Application';
  }
  
  // Vue.js detection
  if (lowerHtml.includes('vue.js') || lowerHtml.includes('__vue') || lowerHtml.includes('vue-')) {
    return 'Vue.js Application';
  }
  
  // Angular detection
  if (lowerHtml.includes('angular') || lowerHtml.includes('ng-version') || lowerHtml.includes('ng-')) {
    return 'Angular Application';
  }
  
  // Generic CMS detection
  if (lowerHtml.includes('/administrator/') || lowerHtml.includes('/admin/') || lowerHtml.includes('cms')) {
    return 'Generic CMS';
  }
  
  return 'Static Website';
}

/**
 * Generate platform-aware prompts for Claude AI
 * Different analysis strategies based on platform type
 */
function generatePlatformAwarePrompt(
  platform: string,
  url: string,
  contentLength: number,
  scriptCount: number,
  linkCount: number,
  formCount: number,
  analysisContent: any
): string {
  const platformLower = platform.toLowerCase();

  // Common metadata section for all platforms
  const commonSection = `WEBSITE: ${url}
PLATFORM: ${platform}

WEBSITE CHARACTERISTICS:
- Content Size: ${Math.round(contentLength / 1024)}KB
- Script Elements: ${scriptCount}
- Stylesheet Links: ${linkCount}
- Forms: ${formCount}

HTML HEAD SECTION:
${analysisContent.headSection}

SCRIPT SOURCES (first 20):
${analysisContent.scriptSources.join('\n')}

STYLESHEET SOURCES (first 15):
${analysisContent.linkSources.join('\n')}

META TAGS:
${analysisContent.metaInfo.join('\n')}

SERVER HEADERS:
${analysisContent.serverHeaders.join('\n')}

HTML CONTENT SAMPLE:
${analysisContent.htmlSample}
`;

  // WordPress-specific prompt
  if (platformLower.includes('wordpress')) {
    return `As an expert WordPress analyst, analyze this WordPress website and detect all installed plugins, themes, and performance optimizations.

${commonSection}

WORDPRESS-SPECIFIC DETECTION FOCUS:
1. **Plugin Detection**: Look for /wp-content/plugins/ paths, plugin-specific CSS/JS files, and HTML data attributes
2. **Theme Detection**: Identify the active theme from /wp-content/themes/ paths
3. **Performance Plugins**: Specifically identify caching, minification, image optimization, and CDN plugins
4. **Security Plugins**: Look for firewall, security hardening, and SSL plugins
5. **SEO Plugins**: Detect Yoast, Rank Math, SEOPress, AIOSEO
6. **E-commerce**: Check for WooCommerce, Easy Digital Downloads, payment gateways
7. **Page Builders**: Identify Elementor, Divi, WPBakery, Beaver Builder, Gutenberg blocks
8. **Form Plugins**: Contact Form 7, Gravity Forms, WPForms, Ninja Forms
9. **Missing Essentials**: Identify if site lacks caching, security, or SEO plugins

PERFORMANCE ANALYSIS:
- Calculate total plugin count and assess if site is "plugin bloated" (>25 plugins)
- Identify heavy plugins that slow down the site
- Recommend consolidation opportunities (redundant plugins)

SECURITY ASSESSMENT:
- Check for vulnerable plugin versions (outdated plugins)
- Assess if basic security plugins are installed
- Recommend security improvements

${getJSONFormatInstructions(platform)}`;
  }

  // Drupal-specific prompt
  if (platformLower.includes('drupal')) {
    return `As an expert Drupal analyst, analyze this Drupal website and detect all installed modules, themes, and configurations.

${commonSection}

DRUPAL-SPECIFIC DETECTION FOCUS:
1. **Module Detection**: Look for /sites/all/modules/, /sites/default/files/, Drupal.settings, module-specific patterns
2. **Core Modules**: Views, Panels, Webform, Pathauto, Metatag, Token
3. **Performance Modules**: Boost, Varnish integration, CSS/JS aggregation
4. **E-commerce**: Drupal Commerce, Ubercart
5. **SEO Modules**: Pathauto, Metatag, XML Sitemap, Redirect
6. **Content Modules**: Views, Panels, Display Suite, Paragraphs
7. **Missing Essentials**: Caching modules, SEO modules, security modules

DRUPAL VERSION DETECTION:
- Attempt to detect Drupal version (7, 8, 9, 10) from patterns
- Note version-specific modules

${getJSONFormatInstructions(platform)}`;
  }

  // Joomla-specific prompt
  if (platformLower.includes('joomla')) {
    return `As an expert Joomla analyst, analyze this Joomla website and detect all installed extensions, components, and modules.

${commonSection}

JOOMLA-SPECIFIC DETECTION FOCUS:
1. **Extension Detection**: Look for /media/jui/, /components/com_*, Joomla.* patterns
2. **Popular Extensions**: K2, VirtueMart, JCE Editor, Akeeba Backup, JCH Optimize, SH404SEF
3. **E-commerce**: VirtueMart, HikaShop
4. **Performance**: JCH Optimize, caching extensions
5. **SEO**: SH404SEF, SEF extensions
6. **Content Management**: K2, Flexicontent
7. **Missing Essentials**: Backup, SEO, security extensions

${getJSONFormatInstructions(platform)}`;
  }

  // Shopify-specific prompt
  if (platformLower.includes('shopify')) {
    return `As an expert Shopify analyst, analyze this Shopify store and detect all installed apps, themes, and integrations.

${commonSection}

SHOPIFY-SPECIFIC DETECTION FOCUS:
1. **App Detection**: Look for app-specific JavaScript, third-party integrations, API calls
2. **Marketing Apps**: Klaviyo, Privy, OptinMonster, email marketing
3. **Review Apps**: Judge.me, Loox, Yotpo, product reviews
4. **Upsell Apps**: Bold Upsell, ReConvert, cross-sell apps
5. **Analytics**: Google Analytics, Facebook Pixel, conversion tracking
6. **Shipping**: ShipStation, shipping calculator apps
7. **Theme**: Identify Shopify theme being used
8. **Missing Essentials**: Reviews, email marketing, abandoned cart recovery, analytics

CONVERSION OPTIMIZATION:
- Assess if store has review apps (social proof)
- Check for abandoned cart recovery
- Identify upsell/cross-sell opportunities
- Verify analytics and pixel tracking

${getJSONFormatInstructions(platform)}`;
  }

  // Magento-specific prompt
  if (platformLower.includes('magento')) {
    return `As an expert Magento analyst, analyze this Magento store and detect all installed extensions, modules, and optimizations.

${commonSection}

MAGENTO-SPECIFIC DETECTION FOCUS:
1. **Extension Detection**: Look for /static/frontend/, Mage.*, magento-specific patterns
2. **Performance Extensions**: Full-page cache, Varnish, Redis integration
3. **Marketing**: Email marketing, customer segmentation, loyalty programs
4. **Payment Gateways**: PayPal, Stripe, Authorize.net
5. **Shipping**: Multi-carrier shipping, table rate shipping
6. **SEO**: SEO Suite Pro, meta tag management
7. **Missing Essentials**: Performance optimization, security extensions

${getJSONFormatInstructions(platform)}`;
  }

  // PrestaShop-specific prompt
  if (platformLower.includes('prestashop')) {
    return `As an expert PrestaShop analyst, analyze this PrestaShop store and detect all installed modules and themes.

${commonSection}

PRESTASHOP-SPECIFIC DETECTION FOCUS:
1. **Module Detection**: Look for /modules/, /themes/, PrestaShop-specific patterns
2. **Performance**: Caching modules, image optimization
3. **Marketing**: Email marketing, social media integration
4. **Payment**: Payment gateway modules
5. **SEO**: SEO modules, URL rewriting
6. **Missing Essentials**: Performance, security, marketing modules

${getJSONFormatInstructions(platform)}`;
  }

  // Wix/Squarespace/Webflow (Website Builders)
  if (platformLower.includes('wix') || platformLower.includes('squarespace') || platformLower.includes('webflow')) {
    return `As an expert website builder analyst, analyze this ${platform} website and detect integrations, apps, and optimizations.

${commonSection}

${platform.toUpperCase()}-SPECIFIC DETECTION FOCUS:
1. **Integrations**: Third-party scripts, APIs, external services
2. **Analytics**: Google Analytics, Facebook Pixel, conversion tracking
3. **Marketing Tools**: Email collection, popup forms, chat widgets
4. **E-commerce**: Payment processors, cart functionality (if applicable)
5. **SEO Tools**: Meta tag management, sitemap generation
6. **Performance**: CDN usage, image optimization, lazy loading
7. **Missing Essentials**: Analytics, SEO optimization, mobile optimization

PLATFORM LIMITATIONS ASSESSMENT:
- Note any performance limitations due to platform constraints
- Identify third-party integrations that slow down the site
- Recommend optimizations within platform capabilities

${getJSONFormatInstructions(platform)}`;
  }

  // Custom/React/Next.js/Vue (JavaScript Apps)
  if (platformLower.includes('react') || platformLower.includes('next') || platformLower.includes('vue') ||
      platformLower.includes('angular') || platformLower.includes('gatsby') || platformLower.includes('static') ||
      platformLower.includes('custom')) {
    return `As an expert web performance analyst, analyze this ${platform} website and identify performance issues, optimizations, and integration opportunities.

${commonSection}

CUSTOM SITE / JAVASCRIPT APP ANALYSIS FOCUS:
Since this is a custom-built website (not a traditional CMS), focus on:

1. **Performance Issues**:
   - Render-blocking resources (unoptimized CSS/JS)
   - Large JavaScript bundles
   - Unoptimized images
   - Missing lazy loading
   - No code splitting
   - Excessive DOM size
   - Long initial load time

2. **Missing Optimizations**:
   - CDN usage (Cloudflare, Fastly, CloudFront)
   - Image optimization (WebP, lazy loading, responsive images)
   - Minification and compression (Gzip, Brotli)
   - HTTP/2 or HTTP/3 support
   - Caching headers
   - Resource hints (preload, prefetch, preconnect)

3. **Third-Party Integrations** (these act like "plugins"):
   - Analytics (Google Analytics, Plausible, Mixpanel)
   - Error tracking (Sentry, Rollbar, Bugsnag)
   - A/B testing (Optimizely, VWO, Google Optimize)
   - Chat widgets (Intercom, Drift, Zendesk)
   - Marketing tools (HubSpot, Mailchimp, Facebook Pixel)
   - Payment processors (Stripe, PayPal)

4. **Framework-Specific Issues**:
   - React: Check for unnecessary re-renders, large bundle size
   - Next.js: Verify SSR/SSG is being used, check for optimization opportunities
   - Vue: Check for Vuex state management overhead
   - Check if framework best practices are followed

5. **Conversion Blockers**:
   - JavaScript errors that break functionality
   - Broken forms or API calls
   - Missing mobile responsiveness
   - Poor accessibility

IMPORTANT: For custom sites, focus on PERFORMANCE ISSUES and INTEGRATION DETECTION rather than traditional "plugins".
Report third-party services as if they were plugins (e.g., "Google Analytics" as an analytics plugin).

${getJSONFormatInstructions(platform)}`;
  }

  // Generic fallback prompt
  return `As an expert web technology analyst, analyze this ${platform} website and provide comprehensive extension/plugin/integration detection.

${commonSection}

DETECTION FOCUS:
1. Identify all third-party integrations and services
2. Detect performance optimization tools
3. Identify analytics and tracking systems
4. Assess security measures in place
5. Detect marketing and conversion tools
6. Identify missing essential functionality

${getJSONFormatInstructions(platform)}`;
}

/**
 * Get consistent JSON format instructions for Claude
 */
function getJSONFormatInstructions(platform: string): string {
  return `
Provide a comprehensive analysis in this JSON format:

{
  "platform": "${platform}",
  "platformVersion": "[detected version if possible]",
  "detectedPlugins": [
    {
      "name": "[plugin/extension/module/app name]",
      "category": "[security|performance|seo|ecommerce|analytics|social|backup|forms|page-builder|content|payment|marketing|integration|utility|theme|other]",
      "subcategory": "[specific subcategory like 'caching', 'firewall', 'social-sharing', etc.]",
      "confidence": "[high|medium|low]",
      "version": "[version if detectable]",
      "description": "[what this plugin/integration does]",
      "riskLevel": "[low|medium|high|critical]",
      "performanceImpact": "[minimal|low|medium|high]",
      "recommendations": ["specific recommendations for this plugin"],
      "detectionEvidence": ["specific HTML/CSS/JS evidence found"]
    }
  ],
  "securityAssessment": {
    "overallRisk": "[low|medium|high|critical]",
    "vulnerablePlugins": ["list of plugin names with known issues"],
    "recommendations": ["security-specific recommendations"]
  },
  "performanceAnalysis": {
    "heavyPlugins": ["plugins/integrations that significantly impact performance"],
    "optimizationOpportunities": ["specific performance improvement suggestions"],
    "estimatedSpeedImpact": "[description of how plugins affect loading speed]"
  },
  "businessInsights": {
    "pluginPurpose": "[what the website is trying to achieve based on plugins/integrations]",
    "businessType": "[inferred business type from plugin usage]",
    "recommendedImprovements": ["business-focused plugin recommendations"],
    "missingEssentials": ["essential plugins/features this site should have]"
  },
  "conflicts": {
    "redundantPlugins": ["plugins that provide overlapping functionality"],
    "potentialConflicts": ["plugins that might conflict with each other"]
  }
}

IMPORTANT GUIDELINES:
- Only detect plugins/extensions/integrations you're confident about based on clear evidence
- Provide specific evidence for each detection
- Be realistic about performance impact
- Prioritize actionable recommendations
- For custom sites: Report third-party services as "plugins" (e.g., Google Analytics)
- Focus on business value, not just technical details`;
}